# supabase/config.toml

[api]
port = 54321
schemas = ["public", "storage", "graphql"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15
[db.pooler]
enabled = false
port = 6543
max_client_conn = 100

[studio]
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://id-preview--88c4857f-5609-41fb-b312-b8dd1cec7b45.lovable.app/**", "https://mobiwave-nexus-platform-36.lovable.app/**", "https://preview--mobiwave-nexus-platform-36.lovable.app/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
[auth.mfa]
max_enrolled_factors = 10
[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400
[auth.email.template]
[auth.sms]
enable_signup = false
[auth.sms.template]
[auth.phone]
[auth.external]
[auth.external.apple]
enabled = false
client_id = ""
secret = ""
[auth.external.azure]
enabled = false
client_id = ""
secret = ""
skip_nonce_check = false
[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
[auth.external.discord]
enabled = false
client_id = ""
secret = ""
[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
[auth.external.figma]
enabled = false
client_id = ""
secret = ""
[auth.external.github]
enabled = false
client_id = ""
secret = ""
[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
[auth.external.google]
enabled = false
client_id = ""
secret = ""
skip_nonce_check = false
[auth.external.keycloak]
enabled = false
url = ""
client_id = ""
secret = ""
[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
[auth.external.notion]
enabled = false
client_id = ""
secret = ""
[auth.external.slack]
enabled = false
client_id = ""
secret = ""
[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
[auth.external.workos]
enabled = false
url = ""
client_id = ""
secret = ""
[auth.external.zoom]
enabled = false
client_id = ""
secret = ""

[analytics]
enabled = false